---
sidebar: sidebar 
permalink: cyber-vault/ontap-cyber-vault-ps-consider.html 
keywords: Cyber vault, powershell, script, configuration, validation, hardening 
summary: 이는 ONTAP 기반 사이버 볼트를 구성, 강화 및 검증하기 위한 NetApp ONTAP 솔루션입니다. 
---
= 추가 고려 사항
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP 기반 사이버 볼트를 설계하고 배포할 때는 추가로 고려해야 할 사항이 있습니다.



== 용량 크기 고려 사항

ONTAP 사이버 볼트 대상 볼륨에 필요한 디스크 공간의 양은 다양한 요소에 따라 달라지는데, 그 중 가장 중요한 요소는 소스 볼륨의 데이터 변경 속도입니다.  대상 볼륨의 백업 일정과 스냅샷 일정은 모두 대상 볼륨의 디스크 사용량에 영향을 미치며, 소스 볼륨의 변경 속도는 일정하지 않을 가능성이 높습니다.  최종 사용자나 애플리케이션 동작의 향후 변경 사항을 수용하는 데 필요한 것보다 더 많은 저장 용량을 버퍼로 제공하는 것이 좋습니다.

ONTAP 에서 1개월 동안 보존할 관계의 크기를 조정하려면 기본 데이터 세트의 크기, 데이터 변경률(일일 변경률), 중복 제거 및 압축 절감(해당되는 경우)을 포함한 여러 요소를 기반으로 저장 요구 사항을 계산해야 합니다.

단계별 접근 방식은 다음과 같습니다.

첫 번째 단계는 사이버 볼트로 보호하고 있는 소스 볼륨의 크기를 아는 것입니다.  이는 사이버 보관소 목적지에 처음 복제되는 기본 데이터 양입니다.  다음으로, 데이터 세트에 대한 일일 변화율을 추정합니다.  이는 매일 변경되는 데이터의 비율입니다.  데이터의 동적성을 잘 이해하는 것이 중요합니다.

예를 들어:

* 1차 데이터 세트 크기 = 5TB
* 일일 변화율 = 5% (0.05)
* 중복 제거 및 압축 효율성 = 50% (0.50)


이제 계산을 살펴보겠습니다.

* 일일 데이터 변경률을 계산합니다.
+
`Changed data per day = 5000 * 5% = 250GB`

* 30일 동안 변경된 총 데이터를 계산합니다.
+
`Total changed data in 30 days = 250 GB * 30 = 7.5TB`

* 필요한 총 저장 공간을 계산하세요.
+
`TOTAL = 5TB + 7.5TB = 12.5TB`

* 중복 제거 및 압축 절감을 적용합니다.
+
`EFFECTIVE = 12.5TB * 50% = 6.25TB`



*저장 요구 사항 요약*

* 효율성이 없다면 30일 치의 사이버 보관소 데이터를 저장하려면 *12.5TB*가 필요할 것입니다.
* 50% 효율성으로 보면 중복 제거 및 압축 후 *6.25TB*의 저장 공간이 필요합니다.



NOTE: 스냅샷 복사본에는 메타데이터로 인해 추가적인 오버헤드가 발생할 수 있지만, 일반적으로 이는 사소합니다.


NOTE: 하루에 여러 번 백업을 수행하는 경우 매일 수행되는 스냅샷 복사본 수에 따라 계산을 조정하세요.


NOTE: 시간 경과에 따른 데이터 증가를 고려하여 미래에도 대응할 수 있는 크기 조정을 보장합니다.



== 기본/소스에 대한 성능 영향

데이터 전송은 풀 작업이기 때문에 기본 저장소 성능에 미치는 영향은 작업 부하, 데이터 볼륨 및 백업 빈도에 따라 달라질 수 있습니다.  그러나 데이터 전송은 데이터 보호 및 백업 작업을 사이버 볼트 저장 시스템으로 오프로드하도록 설계되었기 때문에 기본 시스템에 미치는 전반적인 성능 영향은 일반적으로 적당하고 관리 가능합니다.  초기 관계 설정 및 첫 번째 전체 백업 중에 상당한 양의 데이터가 기본 시스템에서 사이버 볼트 시스템( SnapLock Compliance 볼륨)으로 전송됩니다.  이로 인해 기본 시스템의 네트워크 트래픽과 I/O 부하가 증가할 수 있습니다.  최초의 전체 백업이 완료되면 ONTAP 마지막 백업 이후 변경된 블록만 추적하고 전송하면 됩니다.  이로 인해 초기 복제에 비해 I/O 부하가 훨씬 작아집니다.  증분 업데이트는 효율적이며 기본 저장소 성능에 미치는 영향이 최소화됩니다.  볼트 프로세스는 백그라운드에서 실행되므로 기본 시스템의 프로덕션 작업 부하를 방해할 가능성이 줄어듭니다.

* 스토리지 시스템에 추가적인 부하를 처리할 수 있는 충분한 리소스(CPU, 메모리, IOP)가 있는지 확인하면 성능에 미치는 영향을 완화할 수 있습니다.

