---
sidebar: sidebar 
keywords: Cyber vault, cybervault, cyber-vault, data protection, security, ransomware, ONTAP, hardening 
permalink: cyber-vault/ontap-cyber-vault-interop.html 
summary: 사이버 볼트 상호 운용성 
---
= 사이버 볼트 상호 운용성
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
ONTAP 하드웨어와 소프트웨어를 사용하여 사이버 볼트 구성을 생성할 수 있습니다.



== ONTAP 하드웨어 권장 사항

모든 ONTAP 통합 물리적 어레이는 사이버 볼트 구현에 사용될 수 있습니다.

* FAS 하이브리드 스토리지는 가장 비용 효율적인 솔루션을 제공합니다.
* AFF C 시리즈는 가장 효율적인 전력 소비와 밀도를 제공합니다.
* AFF A-Series는 최고의 RTO를 제공하는 가장 성능이 뛰어난 플랫폼입니다.  최근 발표된 최신 AFF A-시리즈를 통해 이 플랫폼은 성능 저하 없이 최고의 스토리지 효율성을 제공할 것입니다.




== ONTAP 소프트웨어 권장 사항

ONTAP 9.14.1부터 SnapMirror 관계의 SnapMirror 정책에서 특정 SnapMirror 레이블에 대한 보존 기간을 지정할 수 있으므로 소스 볼륨에서 대상 볼륨으로 복제된 스냅샷 복사본이 규칙에 지정된 보존 기간 동안 보존됩니다.  보존 기간이 지정되지 않으면 대상 볼륨의 기본 보존 기간이 사용됩니다.

ONTAP 9.13.1부터 SnapLock 볼트 관계의 대상 SnapLock 볼륨에서 잠긴 스냅샷 복사본을 즉시 복원할 수 있습니다. 이를 위해 FlexClone 생성합니다. 자세히 알아보세요 link:https://docs.netapp.com/us-en/ontap/volumes/create-flexclone-task.html?q=volume+clone["SnapLock 유형으로 FlexClone 볼륨 생성"^] .



== MetroCluster 구성

MetroCluster 구성의 경우 다음 사항을 알고 있어야 합니다.

* SnapVault 관계는 동기화 소스 SVM 간에만 생성할 수 있으며, 동기화 소스 SVM과 동기화 대상 SVM 간에는 생성할 수 없습니다.
* 동기화 소스 SVM의 볼륨에서 데이터 제공 SVM으로 SnapVault 관계를 생성할 수 있습니다.
* 데이터 제공 SVM의 볼륨에서 동기화 소스 SVM의 DP 볼륨으로 SnapVault 관계를 생성할 수 있습니다.

