---
sidebar: sidebar 
permalink: automation/getting-started.html 
summary: NetApp 솔루션 자동화를 통해 고객은 많은 일반적인 인프라 및 애플리케이션 작업의 배포, 구성 및 실행을 자동화할 수 있습니다. 
keywords: netapp, awx, tower, ansible tower, solutions, automation, ansible, getting, started 
---
= NetApp 솔루션 자동화 시작하기
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ../media/


[role="lead"]
NetApp 솔루션 자동화는 NetApp 솔루션에서 사용되는 일반적인 작업의 대부분에 대해 단순성과 반복성을 제공합니다.

솔루션 자동화를 실행하기 전에 자동화가 실행되는 방법에 대한 환경을 구성해야 합니다.  명령줄이나 AWX 또는 Tower와 같은 도구를 통해 자동화를 실행하는 옵션이 있습니다.

다음 섹션에서는 지정된 각 환경에 대한 환경을 구성하는 데 필요한 단계를 간략하게 설명합니다.

.RHEL/CentOS에서 CLI 배포를 위한 Ansible Control Node 설정
[%collapsible%open]
====
. Ansible 제어 노드에 대한 요구 사항:
+
.. 다음 패키지가 설치된 RHEL/CentOS 머신:
+
... Python3
... Pip3
... Ansible(2.10.0 이상 버전)
... 깃






위의 요구 사항이 설치되지 않은 새 RHEL/CentOS 머신이 있는 경우 아래 단계에 따라 해당 머신을 Ansible 제어 노드로 설정하세요.

. RHEL-8/RHEL-7에 대한 Ansible 저장소 활성화
+
.. RHEL-8의 경우(루트로 아래 명령을 실행하세요)
+
[source, cli]
----
subscription-manager repos --enable ansible-2.9-for-rhel-8-x86_64-rpms
----
.. RHEL-7의 경우(아래 명령을 루트로 실행하세요)
+
[source, cli]
----
subscription-manager repos --enable rhel-7-server-ansible-2.9-rpms
----


. 아래 내용을 터미널에 붙여넣으세요
+
[source, cli]
----
sudo yum -y install python3 >> install.log
sudo yum -y install python3-pip >> install.log
python3 -W ignore -m pip --disable-pip-version-check install ansible >> install.log
sudo yum -y install git >> install.log
----


====
.Ubuntu/Debian에서 CLI 배포를 위한 Ansible Control Node 설정
[%collapsible%open]
====
. Ansible 제어 노드에 대한 요구 사항:
+
.. 다음 패키지가 설치된 Ubuntu/Debian 머신:
+
... Python3
... Pip3
... Ansible(2.10.0 이상 버전)
... 깃






위의 요구 사항이 설치되지 않은 새 Ubuntu/Debian 머신이 있는 경우 아래 단계에 따라 해당 머신을 Ansible 제어 노드로 설정하세요.

. 아래 내용을 터미널에 붙여넣으세요
+
[source, cli]
----
sudo apt-get -y install python3 >> outputlog.txt
sudo apt-get -y install python3-pip >> outputlog.txt
python3 -W ignore -m pip --disable-pip-version-check install ansible >> outputlog.txt
sudo apt-get -y install git >> outputlog.txt
----


====
.Tower/AWX 배포를 위한 Ansible Tower 또는 AWX 설정
[%collapsible%open]
====
이 섹션에서는 NetApp 자동화 솔루션을 사용하기 위한 환경을 준비하는 AWX/Ansible Tower의 매개변수를 구성하는 데 필요한 단계를 설명합니다.

. 인벤토리를 구성합니다.
+
.. 리소스 → 인벤토리 → 추가로 이동하여 인벤토리 추가를 클릭합니다.
.. 이름과 조직 세부 정보를 입력하고 저장을 클릭하세요.
.. 인벤토리 페이지에서 방금 만든 인벤토리 리소스를 클릭합니다.
.. 재고 변수가 있으면 변수 필드에 붙여넣습니다.
.. 그룹 하위 메뉴로 가서 추가를 클릭합니다.
.. 그룹 이름을 입력하고, 필요한 경우 그룹 변수를 복사한 다음 저장을 클릭합니다.
.. 생성된 그룹을 클릭하고 호스트 하위 메뉴로 가서 새 호스트 추가를 클릭합니다.
.. 호스트 이름과 호스트의 IP 주소를 입력하고, 필요한 경우 호스트 변수를 붙여넣은 다음 저장을 클릭합니다.


. 자격 증명 유형을 만듭니다.  ONTAP, Element, VMware 또는 기타 HTTPS 기반 전송 연결이 포함된 솔루션의 경우 사용자 이름 및 비밀번호 항목과 일치하도록 자격 증명 유형을 구성해야 합니다.
+
.. 관리 → 자격 증명 유형으로 이동하여 추가를 클릭합니다.
.. 이름과 설명을 입력하세요.
.. 다음 내용을 입력 구성에 붙여넣으세요.




[listing]
----
fields:
- id: username
type: string
label: Username
- id: password
type: string
label: Password
secret: true
- id: vsadmin_password
type: string
label: vsadmin_password
secret: true
----
. 다음 내용을 Injector Configuration에 붙여넣습니다.


[listing]
----
extra_vars:
password: '{{ password }}'
username: '{{ username }}'
vsadmin_password: '{{ vsadmin_password }}'
----
. 자격 증명을 구성합니다.
+
.. 리소스 → 자격 증명으로 이동하여 추가를 클릭합니다.
.. 이름과 조직 세부정보를 입력하세요.
.. 올바른 자격 증명 유형을 선택하세요. 표준 SSH 로그인을 사용하려는 경우 머신 유형을 선택하거나, 직접 만든 사용자 정의 자격 증명 유형을 선택하세요.
.. 나머지 해당 세부 정보를 입력하고 저장을 클릭하세요.


. 프로젝트를 구성합니다.
+
.. 리소스 → 프로젝트로 이동하여 추가를 클릭합니다.
.. 이름과 조직 세부정보를 입력하세요.
.. 소스 제어 자격 증명 유형으로 Git을 선택합니다.
.. 특정 솔루션에 해당하는 소스 제어 URL(또는 git 복제 URL)을 붙여넣습니다.
.. 선택적으로 Git URL에 대한 액세스가 제어되는 경우 소스 제어 자격 증명에 해당 자격 증명을 만들어 첨부합니다.
.. Save를 클릭합니다.


. 작업 템플릿을 구성합니다.
+
.. 리소스 → 템플릿 → 추가로 이동하여 작업 템플릿 추가를 클릭합니다.
.. 이름과 설명을 입력하세요.
.. 작업 유형을 선택합니다. 실행은 플레이북을 기반으로 시스템을 구성하고, 확인은 실제로 시스템을 구성하지 않고 플레이북의 테스트 실행을 수행합니다.
.. 플레이북에 해당하는 인벤토리, 프로젝트 및 자격 증명을 선택합니다.
.. 작업 템플릿의 일부로 실행할 플레이북을 선택하세요.
.. 일반적으로 변수는 런타임 중에 붙여넣어집니다.  따라서 런타임 중에 변수를 채우라는 메시지를 받으려면 변수 필드에 해당하는 '실행 시 메시지 표시' 확인란을 선택하세요.
.. 필요에 따라 기타 세부 정보를 입력하고 '저장'을 클릭하세요.


. 작업 템플릿을 실행합니다.
+
.. 리소스 → 템플릿으로 이동합니다.
.. 원하는 템플릿을 클릭한 다음 실행을 클릭합니다.
.. 시작할 때 메시지가 표시되면 모든 변수를 입력한 다음 다시 시작을 클릭합니다.




====
자세한 내용은 다음을 방문하세요.link:https://netapp.io/2018/10/08/getting-started-with-netapp-and-ansible-install-ansible/["NetApp 솔루션 자동화 및 Ansible 시작하기"]

자동화를 요청하려면 다음을 작성하십시오.link:https://github.com/NetAppDocs/netapp-solutions/issues/new?body=%5BRequest%20Automation%5D%0d%0a%0d%0aSolution%20Name:%20%0d%0aRequest%20Title:%20%0d%0aDescription:%0d%0aSuggestions:&title=Request%20Automation%20-%20["자동화 요청 양식"] .
